language: python
python:
 - "3.5"
install:
 - pip install coveralls
 - pip install colorama
script: 
 - make
 - coverage run --source=rpn.py test_rpn.py -m unittest discover
after_success:
 - coveralls