language: python
python:
 - "3.5"
install:
 - pip install coveralls
 - pip install colorama
script: 
 - make
 - coverage run --omit=/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/colorama/* -m unittest discover
after_success:
 - coveralls